import express from "express";

const app = express();
const PORT = process.env.PORT || 3000;

app.get("/", (req, res) => {
  res.send("Hello World from Render2 🚀");
});



const tips = [
  // --- Original 50 ---
  "Use environment variables for secrets.",
  "Always validate API input.",
  "Use caching to improve performance.",
  "Write reusable components in React.",
  "Keep your functions small and focused on one task.",
  "Document your code with meaningful comments, not just 'what' it does.",
  "Use descriptive naming conventions for variables and functions.",
  "Implement rate limiting to protect your API from abuse.",
  "Regularly update your dependencies to patch security vulnerabilities.",
  "Use a linter like ESLint to maintain code consistency.",
  "Write unit tests for critical business logic.",
  "Don't hardcode configuration values; use config files.",
  "Use Git branches for new features and bug fixes.",
  "Perform regular code reviews to catch bugs early.",
  "Optimize images to reduce page load times.",
  "Use a Content Delivery Network (CDN) for static assets.",
  "Follow the DRY (Don't Repeat Yourself) principle.",
  "Use meaningful commit messages in version control.",
  "Understand the time complexity (Big O) of your algorithms.",
  "Use HTTPS for all communication between client and server.",
  "Sanitize user input to prevent XSS and SQL injection.",
  "Implement logging to track errors and system performance.",
  "Use a task runner or build tool like Webpack or Vite.",
  "Keep your CSS modular and avoid global styles where possible.",
  "Use accessibility (a11y) best practices in your web apps.",
  "Learn to use the browser's developer tools effectively.",
  "Profile your application to identify performance bottlenecks.",
  "Use a consistent coding style across your project.",
  "Implement proper error handling and return helpful error messages.",
  "Use pagination for API endpoints that return large datasets.",
  "Avoid deeply nested code by using early returns.",
  "Understand how 'this' works in JavaScript.",
  "Use async/await for more readable asynchronous code.",
  "Leverage browser storage (localStorage, IndexedDB) wisely.",
  "Minimize the number of HTTP requests your application makes.",
  "Use semantic HTML tags for better SEO and accessibility.",
  "Optimize your database queries with proper indexing.",
  "Use a state management library only when necessary.",
  "Keep your production environment as similar to dev as possible.",
  "Automate your deployment process with CI/CD pipelines.",
  "Monitor your application's uptime and health.",
  "Read the documentation for the libraries and frameworks you use.",
  "Stay curious and keep learning new technologies.",
  "Don't be afraid to ask for help or admit when you don't know something.",
  "Take regular breaks to avoid burnout and maintain focus.",
  "Write code for humans first, computers second.",
  "Use 'const' by default and 'let' only when reassignment is needed.",
  "Learn to use the terminal/command line efficiently.",
  "Understand the basics of networking (HTTP, DNS, TCP/IP).",
  "Focus on solving the problem before you worry about the 'perfect' code.",

  // --- Frontend & Web UI ---
  "Use srcset for responsive images to save mobile bandwidth.",
  "Prefer CSS Grid for layouts and Flexbox for alignment.",
  "Implement 'Lazy Loading' for images below the fold.",
  "Keep your interactive elements at least 44x44 pixels for touch targets.",
  "Use rel='noopener noreferrer' when opening external links in a new tab.",
  "Avoid 'Div-soup'; use semantic tags like <main>, <section>, and <article>.",
  "Use a 'Skip to Content' link for keyboard and screen reader users.",
  "Check your site's contrast ratio to ensure readability for visually impaired users.",
  "Use font-display: swap to prevent invisible text during font loading.",
  "Minimize the use of heavy web fonts.",
  "Use CSS variables for easy theme switching (Dark/Light mode).",
  "Avoid inline styles; they make debugging and CSP implementation harder.",
  "Use defer or async when loading external scripts.",
  "Test your UI in 'incognito' mode to ensure no cache-specific bugs.",
  "Utilize the Intersection Observer API for scroll-based animations.",
  "Ensure all form inputs have associated <label> tags.",
  "Use rem units for typography to respect user browser scaling.",
  "Don't disable 'outline' on focused elements without providing a clear alternative.",
  "Use SVGs for icons instead of icon fonts for better performance and control.",
  "Implement a 'Skeleton Loader' to improve perceived performance.",
  "Keep your 'bundle size' in check using tools like BundleAnalyzer.",
  "Use requestIdleCallback for non-essential background tasks.",
  "Avoid using 'index' as a key in React lists if the order can change.",
  "Use Memo and useCallback to prevent unnecessary re-renders in React.",
  "Validate your HTML using the W3C validator occasionally.",
  "Always provide alt text for informative images.",
  "Use box-sizing: border-box globally in your CSS.",
  "Clean up event listeners in useEffect or componentWillUnmount.",
  "Use window.matchMedia to handle JS-based responsive logic.",
  "Implement 'Smooth Scrolling' via CSS for a better UX.",

  // --- Backend & API Design ---
  "Use UUIDs instead of auto-incrementing IDs for public-facing resources.",
  "Implement 'Idempotency Keys' for critical POST requests (like payments).",
  "Follow RESTful naming conventions: use nouns, not verbs, in URLs.",
  "Return the correct HTTP status codes (e.g., 201 for Created, 403 for Forbidden).",
  "Use 'Joi' or 'Zod' for robust schema validation.",
  "Implement Gzip or Brotli compression on the server side.",
  "Use a 'Health Check' endpoint for load balancer monitoring.",
  "Set X-Content-Type-Options: nosniff to prevent MIME-type sniffing.",
  "Use helmet (in Express) to set secure HTTP headers automatically.",
  "Keep your API versioned (e.g., /v1/users) to avoid breaking changes.",
  "Use Connection Pooling for database connections.",
  "Store passwords using strong hashing algorithms like Argon2 or Bcrypt.",
  "Never log sensitive data like passwords or API keys.",
  "Use a 'Circuit Breaker' pattern for calling third-party APIs.",
  "Use structured logging (JSON) for easier searching in production.",
  "Implement 'Soft Deletes' (is_deleted flag) instead of permanent removal.",
  "Use Webhooks for long-running processes instead of polling.",
  "Keep your JWT payloads small; don't store large objects in tokens.",
  "Use AbortController to cancel outgoing fetch requests.",
  "Limit the payload size of incoming requests to prevent DoS attacks.",
  "Use a message queue (Redis, RabbitMQ) for heavy background jobs.",
  "Always set a timeout for outgoing network requests.",
  "Prefer 'Streams' over 'Buffers' when handling large files.",
  "Use database migrations to track schema changes over time.",
  "Implement CORS with a strict whitelist rather than using '*'.",
  "Use 'Prepared Statements' to eliminate the risk of SQL injection.",
  "Sanitize logs to remove PII (Personally Identifiable Information).",
  "Use ETag headers for client-side caching of API responses.",
  "Profile your slowest DB queries and add indexes where needed.",
  "Use a Reverse Proxy like Nginx or Caddy in front of your Node app.",

  // --- Tooling & Workflow ---
  "Use .editorconfig to sync indentation styles across different IDEs.",
  "Learn the most common keyboard shortcuts for your IDE.",
  "Use 'Git Hooks' (Husky) to run tests before every commit.",
  "Set up a README.md that explains how to run the project locally.",
  "Use a .gitignore file to keep node_modules out of version control.",
  "Try 'Pair Programming' to solve complex logic puzzles.",
  "Keep your Pull Requests small and focused on one change.",
  "Use 'Docker' to ensure your app runs the same on every machine.",
  "Master 'Git Rebase' to keep a clean commit history.",
  "Use 'Conventional Commits' (feat:, fix:, chore:) for clarity.",
  "Automate your changelog generation from commit messages.",
  "Use 'Stashing' in Git to quickly switch contexts without committing.",
  "Try 'Test Driven Development' (TDD) for complex utility functions.",
  "Use an API client like Postman or Bruno to test endpoints.",
  "Configure your IDE to 'Format on Save'.",
  "Use 'Prettier' for opinionated, automatic code formatting.",
  "Check for 'Dead Code' (unused functions/variables) regularly.",
  "Use 'Alias Paths' (e.g., @/components) to avoid relative path hell.",
  "Set up an 'Alerting' system for production crashes (Sentry, LogRocket).",
  "Use 'Dependabot' to automate dependency security updates.",
  "Learn to use git bisect to find the exact commit that introduced a bug.",
  "Keep your 'global variables' to an absolute minimum.",
  "Use 'Cherry-picking' to move specific commits between branches.",
  "Document your environment variables in a .env.example file.",
  "Use 'Shell Scripts' to automate repetitive terminal tasks.",
  "Learn the basics of Vim—it is useful when SSH-ing into a server.",
  "Use a 'Monorepo' tool (NX, Turborepo) for managing multiple packages.",
  "Take advantage of 'GitHub Actions' for simple CI tasks.",
  "Use 'Feature Flags' to roll out new features to a small group first.",
  "Keep your local development database seeded with realistic data.",

  // --- Logic & Clean Code ---
  "Always code as if the person who ends up maintaining it is a violent psychopath.",
  "Favour composition over inheritance.",
  "Keep your 'cyclomatic complexity' low by avoiding deep nesting.",
  "Use 'Guard Clauses' to handle edge cases at the start of a function.",
  "Naming a variable is hard—take the time to get it right.",
  "Avoid 'Magic Numbers'; use named constants instead.",
  "Keep functions pure when possible (no side effects).",
  "Don't over-engineer; start with the simplest solution that works.",
  "Premature optimization is the root of all evil.",
  "Leave the code slightly cleaner than you found it (The Boy Scout Rule).",
  "Be explicit, not implicit.",
  "Avoid 'Boolean' parameters; use Enums or named objects for clarity.",
  "Prefer 'Map' and 'Set' over objects for frequent additions/deletions.",
  "Use Object.freeze for constants that should never change.",
  "Understand the difference between 'Deep Copy' and 'Shallow Copy'.",
  "Don't use 'eval()'. Just don't.",
  "Use 'Template Literals' for cleaner string concatenation.",
  "Leverage 'Destructuring' to extract values from objects and arrays.",
  "Use 'Optional Chaining' (?.) to avoid 'cannot read property of undefined'.",
  "Use the 'Nullish Coalescing' operator (??) for default values.",
  "Avoid 'God Objects' that try to do everything.",
  "Follow the 'Single Responsibility Principle' (SRP).",
  "Write code that is easy to delete, not just easy to write.",
  "Minimize 'State' wherever possible; derived data is often better.",
  "Use Promises.all for parallelizing independent async operations.",
  "Avoid using 'var'; stick to 'let' and 'const'.",
  "Use 'Strict Mode' in JavaScript to catch silent errors.",
  "Be careful with 'Floating Point' math; use libraries for financial data.",
  "Use Array.prototype.some and every for cleaner condition checking.",
  "Encapsulate complex logic into custom Hooks or helper functions.",

  // --- Professional Growth & Mindset ---
  "Read other people's code to learn new patterns.",
  "Don't tie your identity to your code; be open to critique.",
  "Explain the problem out loud (Rubber Duck Debugging).",
  "Soft skills are just as important as technical skills.",
  "Learn how to write a good bug report.",
  "Know when to walk away from the screen to let your brain reset.",
  "Invest time in learning the fundamentals (Data Structures, OS, Networking).",
  "Contribute to Open Source to see how large-scale projects work.",
  "Build a side project to explore a technology you don't use at work.",
  "Learn how to estimate tasks by breaking them into the smallest units.",
  "A 'quick fix' usually isn't. Take the time to find the root cause.",
  "The best code is the code you didn't have to write.",
  "Always test your 'happy path' and 'unhappy path'.",
  "Keep a 'Today I Learned' (TIL) log.",
  "Don't chase every new framework; master the core language first.",
  "Understand the business value of the feature you are building.",
  "Learn how to give constructive feedback in code reviews.",
  "Be the person who documents the 'weird' setup steps.",
  "Practice 'Active Listening' during technical meetings.",
  "Don't optimize for a future that might never happen.",
  "Your first solution is rarely your best; refactor.",
  "Learn to say 'No' to unrealistic deadlines or features.",
  "Write for your future self—you will forget this logic in 3 months.",
  "The debugger is your best friend; console.log is just an acquaintance.",
  "Learn how to use Google (and AI) effectively for troubleshooting.",
  "Master the art of the 'Google Search' using advanced operators.",
  "Stay humble—there is always someone who knows something you don't.",
  "Work on your technical writing; clear specs save hours of coding.",
  "Understand the 'Sunk Cost Fallacy' when deciding to scrap a bad approach.",
  "Celebrate the small wins—getting a tricky test to pass feels great!"
];

app.get("/dev-tip", (req, res) => {
  const tip = tips[Math.floor(Math.random() * tips.length)];
  res.json({ tip });
});

app.get("/hello", (req, res) => {
  res.status(200).json({
    status: "success",
    message: "API is healthy ✅",
    timestamp: new Date(),
  });
});

//bible-qoutes
const bibleQuotes = [
  { verse: "Philippians 4:13", text: "I can do all things through Christ who strengthens me.", category: "strength" },
  { verse: "Psalm 23:1", text: "The Lord is my shepherd; I shall not want.", category: "faith" },
  { verse: "Jeremiah 29:11", text: "For I know the plans I have for you, declares the Lord.", category: "hope" },
  { verse: "Proverbs 3:5", text: "Trust in the Lord with all your heart.", category: "faith" },
  { verse: "Isaiah 41:10", text: "Do not fear, for I am with you.", category: "strength" },
  { verse: "Romans 8:28", text: "All things work together for good to those who love God.", category: "hope" },
  { verse: "Matthew 6:33", text: "Seek first the kingdom of God.", category: "faith" },
  { verse: "Psalm 46:1", text: "God is our refuge and strength.", category: "strength" },
  { verse: "Joshua 1:9", text: "Be strong and courageous. Do not be afraid.", category: "strength" },
  { verse: "2 Timothy 1:7", text: "God has not given us a spirit of fear.", category: "strength" },

  { verse: "Psalm 34:8", text: "Taste and see that the Lord is good.", category: "faith" },
  { verse: "Hebrews 11:1", text: "Faith is the substance of things hoped for.", category: "faith" },
  { verse: "Romans 15:13", text: "May the God of hope fill you with joy.", category: "hope" },
  { verse: "John 14:27", text: "Peace I leave with you; my peace I give you.", category: "peace" },
  { verse: "Psalm 55:22", text: "Cast your burden on the Lord.", category: "hope" },
  { verse: "1 Peter 5:7", text: "Cast all your anxiety on Him.", category: "peace" },
  { verse: "Psalm 121:1-2", text: "My help comes from the Lord.", category: "faith" },
  { verse: "Matthew 11:28", text: "Come to me, all who are weary.", category: "peace" },
  { verse: "Isaiah 40:31", text: "Those who hope in the Lord will renew their strength.", category: "strength" },
  { verse: "Psalm 119:105", text: "Your word is a lamp to my feet.", category: "faith" },

  { verse: "Proverbs 16:3", text: "Commit to the Lord whatever you do.", category: "faith" },
  { verse: "John 3:16", text: "For God so loved the world.", category: "love" },
  { verse: "1 Corinthians 13:4", text: "Love is patient, love is kind.", category: "love" },
  { verse: "Psalm 37:4", text: "Delight yourself in the Lord.", category: "hope" },
  { verse: "Romans 12:12", text: "Be joyful in hope, patient in affliction.", category: "hope" },
  { verse: "Colossians 3:23", text: "Work heartily, as for the Lord.", category: "motivation" },
  { verse: "Galatians 6:9", text: "Do not grow weary in doing good.", category: "motivation" },
  { verse: "Ephesians 2:8", text: "For it is by grace you have been saved.", category: "faith" },
  { verse: "Psalm 91:1", text: "Whoever dwells in the shelter of the Most High.", category: "protection" },
  { verse: "Deuteronomy 31:6", text: "Be strong and courageous.", category: "strength" },

  { verse: "Psalm 118:24", text: "This is the day the Lord has made.", category: "joy" },
  { verse: "James 1:5", text: "If any of you lacks wisdom, ask God.", category: "wisdom" },
  { verse: "Proverbs 2:6", text: "For the Lord gives wisdom.", category: "wisdom" },
  { verse: "Ecclesiastes 3:1", text: "There is a time for everything.", category: "wisdom" },
  { verse: "Psalm 27:1", text: "The Lord is my light and salvation.", category: "faith" },
  { verse: "Micah 6:8", text: "Act justly, love mercy, walk humbly.", category: "wisdom" },
  { verse: "Romans 10:9", text: "If you declare Jesus is Lord.", category: "faith" },
  { verse: "John 16:33", text: "Take heart! I have overcome the world.", category: "hope" },
  { verse: "Psalm 62:6", text: "He alone is my rock and salvation.", category: "faith" },
  { verse: "Lamentations 3:22-23", text: "His mercies are new every morning.", category: "hope" },

  { verse: "Matthew 5:16", text: "Let your light shine before others.", category: "motivation" },
  { verse: "Hebrews 13:5", text: "Never will I leave you.", category: "hope" },
  { verse: "Psalm 16:8", text: "I keep my eyes always on the Lord.", category: "faith" },
  { verse: "Isaiah 26:3", text: "You will keep in perfect peace.", category: "peace" },
  { verse: "Proverbs 18:10", text: "The name of the Lord is a strong tower.", category: "protection" },
  { verse: "2 Corinthians 5:7", text: "Walk by faith, not by sight.", category: "faith" },
  { verse: "Mark 9:23", text: "Everything is possible for one who believes.", category: "faith" },
  { verse: "Psalm 145:18", text: "The Lord is near to all who call on Him.", category: "hope" },
  { verse: "Luke 1:37", text: "Nothing will be impossible with God.", category: "faith" },
  { verse: "John 10:10", text: "I have come that they may have life.", category: "life" }
];

app.get("/bible-quote", (req, res) => {
  const random = bibleQuotes[Math.floor(Math.random() * bibleQuotes.length)];

  res.json({
    status: "success",
    data: random
  });
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});